env:
  browser: true
  es6: true
extends: "plugin:react/recommended"
settings:
  react:
    version: detect
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
rules:
  func-names: 0
  object-shorthand: 0
  consistent-return: 0
