apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-capstone-final
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-app
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: react-app
        tier: frontend
    spec:
      containers:
        - name: react-app
          image: adorszasz/udacity-nd9991-capstone:26
          ports:
            - containerPort: 3000
              name: wordpress
---
apiVersion: v1
kind: Service
metadata:
  name: nd-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: react-app
    tier: frontend
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 8080
      nodePort: 30001
