apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: react-app
  namespace: kube-system
  labels:
    k8s-app: react-app
spec:
  selector:
    matchLabels:
      app: react-app
      tier: frontend
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: react-app
        tier: frontend
    spec:
      tolerations:
      # this toleration is to have the daemonset runnable on master nodes
      # remove it if your masters can't run pods
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: react-app
        image: adorszasz/udacity-nd9991-capstone:26
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        ports:
          - containerPort: 3000
            name: react-app
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
---
apiVersion: v1
kind: Service
metadata:
  name: nd-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: react-app
    tier: frontend
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 8080
      nodePort: 30001
