---
# This playbook does a rolling update for all images serially (one at a time).
- hosts: localhost
  serial: 1
  gather_facts: false

  vars_files:
    - vars/main.yml

  tasks:
    - name: Deploy React-App.
      k8s:
        definition: "{{ item }}"
        kubeconfig: "{{ k8s_kubeconfig }}"
        state: present
      loop: "{{ lookup('template', 'react-app/main.yml') | from_yaml_all | list }}"

    - name: Get load balancer DNS name.
      k8s_info:
        kubeconfig: "{{ k8s_kubeconfig }}"
        kind: Service
        name: react-app
        namespace: default
      register: reactapp_svc
