---
- hosts: localhost
  gather_facts: false

  vars_files:
    - vars/main.yml

  tasks:
    - name: Ensure botocore and boto3 modules are installed
      pip:
        name: ["boto3", "botocore"]
        extra_args: "--user"

    - name: Ensure VPC exists via CloudFormation.
      cloudformation:
        stack_name: capstone-eks-vpc
        state: present
        region: "{{ aws_region }}"
        disable_rollback: false
        template: cloudformation/vpc.yml
        template_parameters:
          Region: "{{ aws_region }}"
        tags:
          stack: capstone-eks-vpc
          application: capstone-eks
      register: vpc_info

    - name: Add to stack_outputs.
      set_fact:
        stack_outputs: "{{ stack_outputs | combine(vpc_info['stack_outputs']) }}"

    - name: Ensure EKS Cluster exists via CloudFormation.
      cloudformation:
        stack_name: capstone-eks-cluster
        state: present
        region: "{{ aws_region }}"
        disable_rollback: false
        template: cloudformation/eks-cluster.yml
        template_parameters:
          ClusterName: "{{ eks_cluster_name }}"
          KubernetesVersion: "{{ eks_kubernetes_version }}"
          Subnets: "{{ stack_outputs.Subnets }}"
          VpcId: "{{ stack_outputs.VpcId }}"
        tags:
          stack: capstone-eks-cluster
          application: capstone-eks
      register: eks_cluster_info

    - name: Add to stack_outputs.
      set_fact:
        stack_outputs: "{{ stack_outputs | combine(eks_cluster_info['stack_outputs']) }}"

    - name: Ensure EKS Node Group exists via CloudFormation.
      cloudformation:
        stack_name: capstone-eks-nodegroup
        state: present
        region: "{{ aws_region }}"
        disable_rollback: false
        template: cloudformation/eks-nodegroup.yml
        template_parameters:
          ClusterName: "{{ eks_cluster_name }}"
          NodeGroupName: "{{ eks_nodegroup_name }}"
          NodeGroupDesiredCapacity: "{{ eks_nodegroup_cluster_size }}"
          NodeInstanceType: "{{ eks_nodegroup_instance_type }}"
          Subnets: "{{ stack_outputs.Subnets }}"
        tags:
          stack: capstone-eks-nodegroup
          application: capstone-eks
      register: eks_nodegroup_info
