pipeline {    
    agent any
    
    environment {
        CI = 'true' 
        registry = "adorszasz/udacity-nd9991-capstone"
    }
    stages {
        stage('Prepare EKS-Stack') {
            steps {
                sh 'AWS_PROFILE=default ansible-playbook -i ../eks/inventory ../eks/main.yml'
            }
        }
        stage('Deploy image into the cluster') {
            steps{
                sh "AWS_PROFILE=default ansible-playbook -i ../eks/inventory ../eks/deploy.yml"
            }
        }
    }
}
